#!/bin/bash

terraform fmt -recursive

# Git pre-commit hook: Добавление новой строки в конце текстовых файлов, если отсутствует

# Получаем список всех отслеживаемых файлов
all_files=$(git ls-files)

# Функция для проверки, является ли файл текстовым
is_text_file() {
  # Команда file выводит тип файла; если вывод содержит "text", считаем файл текстовым
  if file "$1" | grep -q 'text'; then
    return 0
  else
    return 1
  fi
}

# Обрабатываем каждый отслеживаемый файл
for file in $all_files; do
  # Проверяем, что файл существует и является обычным файлом
  if [ -f "$file" ]; then
    # Проверяем, что файл текстовый
    if is_text_file "$file"; then
      # Извлекаем последний символ файла
      last_char=$(tail -c 1 "$file")
      # Если файл не заканчивается новой строкой, добавляем её
      if [ "$last_char" != "" ] && [ "$last_char" != $'\n' ]; then
        echo "Добавление новой строки в конец файла: $file"
        echo "" >> "$file"
        # Обновляем индекс Git, чтобы изменения попали в коммит
        git add "$file"
      fi
    fi
  fi
done

git update-index --again
